#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsouConsole
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RedianHedian")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TsouConsole.Properties.Settings.Default.RedianHedianConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<gprs_cell_rp> gprs_cell_rp
		{
			get
			{
				return this.GetTable<gprs_cell_rp>();
			}
		}
		
		public System.Data.Linq.Table<gprs_ci> gprs_ci
		{
			get
			{
				return this.GetTable<gprs_ci>();
			}
		}
		
		public System.Data.Linq.Table<gprs_rpp> gprs_rpp
		{
			get
			{
				return this.GetTable<gprs_rpp>();
			}
		}
		
		public System.Data.Linq.Table<gprs_tousu> gprs_tousu
		{
			get
			{
				return this.GetTable<gprs_tousu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gprs_cell_rp")]
	public partial class gprs_cell_rp
	{
		
		private string _CELL;
		
		private string _NOPDCH;
		
		private string _RP;
		
		public gprs_cell_rp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELL", DbType="NVarChar(255)")]
		public string CELL
		{
			get
			{
				return this._CELL;
			}
			set
			{
				if ((this._CELL != value))
				{
					this._CELL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOPDCH", DbType="NVarChar(255)")]
		public string NOPDCH
		{
			get
			{
				return this._NOPDCH;
			}
			set
			{
				if ((this._NOPDCH != value))
				{
					this._NOPDCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RP", DbType="NVarChar(255)")]
		public string RP
		{
			get
			{
				return this._RP;
			}
			set
			{
				if ((this._RP != value))
				{
					this._RP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gprs_ci")]
	public partial class gprs_ci
	{
		
		private string _cell_name;
		
		private string _cell_no;
		
		private string _基站名;
		
		private string _基站代号;
		
		private string _bsc;
		
		private string _latitude;
		
		private string _longitude;
		
		public gprs_ci()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_name", DbType="NVarChar(255)")]
		public string cell_name
		{
			get
			{
				return this._cell_name;
			}
			set
			{
				if ((this._cell_name != value))
				{
					this._cell_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_no", DbType="NVarChar(255)")]
		public string cell_no
		{
			get
			{
				return this._cell_no;
			}
			set
			{
				if ((this._cell_no != value))
				{
					this._cell_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_基站名", DbType="NVarChar(255)")]
		public string 基站名
		{
			get
			{
				return this._基站名;
			}
			set
			{
				if ((this._基站名 != value))
				{
					this._基站名 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_基站代号", DbType="NVarChar(255)")]
		public string 基站代号
		{
			get
			{
				return this._基站代号;
			}
			set
			{
				if ((this._基站代号 != value))
				{
					this._基站代号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bsc", DbType="NVarChar(255)")]
		public string bsc
		{
			get
			{
				return this._bsc;
			}
			set
			{
				if ((this._bsc != value))
				{
					this._bsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="NVarChar(255)")]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this._latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="NVarChar(255)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gprs_rpp")]
	public partial class gprs_rpp
	{
		
		private System.Nullable<System.DateTime> _时间;
		
		private string _BSC;
		
		private System.Nullable<int> _RPPID;
		
		private System.Nullable<int> _RPPLOAD;
		
		public gprs_rpp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时间", DbType="DateTime")]
		public System.Nullable<System.DateTime> 时间
		{
			get
			{
				return this._时间;
			}
			set
			{
				if ((this._时间 != value))
				{
					this._时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSC", DbType="NVarChar(254)")]
		public string BSC
		{
			get
			{
				return this._BSC;
			}
			set
			{
				if ((this._BSC != value))
				{
					this._BSC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPPID", DbType="Int")]
		public System.Nullable<int> RPPID
		{
			get
			{
				return this._RPPID;
			}
			set
			{
				if ((this._RPPID != value))
				{
					this._RPPID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPPLOAD", DbType="Int")]
		public System.Nullable<int> RPPLOAD
		{
			get
			{
				return this._RPPLOAD;
			}
			set
			{
				if ((this._RPPLOAD != value))
				{
					this._RPPLOAD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gprs_tousu")]
	public partial class gprs_tousu
	{
		
		private string _请求编号;
		
		private string _日期;
		
		private System.Nullable<System.DateTime> _受理时间;
		
		private string _服务请求类别;
		
		private string _受理工号;
		
		private string _操作状态;
		
		private string _用户级别;
		
		private string _用户品牌;
		
		private string _业务内容;
		
		private string _经度;
		
		private string _纬度;
		
		public gprs_tousu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_请求编号", DbType="NVarChar(255)")]
		public string 请求编号
		{
			get
			{
				return this._请求编号;
			}
			set
			{
				if ((this._请求编号 != value))
				{
					this._请求编号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_日期", DbType="NVarChar(255)")]
		public string 日期
		{
			get
			{
				return this._日期;
			}
			set
			{
				if ((this._日期 != value))
				{
					this._日期 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_受理时间", DbType="DateTime")]
		public System.Nullable<System.DateTime> 受理时间
		{
			get
			{
				return this._受理时间;
			}
			set
			{
				if ((this._受理时间 != value))
				{
					this._受理时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_服务请求类别", DbType="NVarChar(255)")]
		public string 服务请求类别
		{
			get
			{
				return this._服务请求类别;
			}
			set
			{
				if ((this._服务请求类别 != value))
				{
					this._服务请求类别 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_受理工号", DbType="NVarChar(255)")]
		public string 受理工号
		{
			get
			{
				return this._受理工号;
			}
			set
			{
				if ((this._受理工号 != value))
				{
					this._受理工号 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_操作状态", DbType="NVarChar(255)")]
		public string 操作状态
		{
			get
			{
				return this._操作状态;
			}
			set
			{
				if ((this._操作状态 != value))
				{
					this._操作状态 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_用户级别", DbType="NVarChar(255)")]
		public string 用户级别
		{
			get
			{
				return this._用户级别;
			}
			set
			{
				if ((this._用户级别 != value))
				{
					this._用户级别 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_用户品牌", DbType="NVarChar(255)")]
		public string 用户品牌
		{
			get
			{
				return this._用户品牌;
			}
			set
			{
				if ((this._用户品牌 != value))
				{
					this._用户品牌 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_业务内容", DbType="NVarChar(4000)")]
		public string 业务内容
		{
			get
			{
				return this._业务内容;
			}
			set
			{
				if ((this._业务内容 != value))
				{
					this._业务内容 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_经度", DbType="NVarChar(255)")]
		public string 经度
		{
			get
			{
				return this._经度;
			}
			set
			{
				if ((this._经度 != value))
				{
					this._经度 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_纬度", DbType="NVarChar(255)")]
		public string 纬度
		{
			get
			{
				return this._纬度;
			}
			set
			{
				if ((this._纬度 != value))
				{
					this._纬度 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
